### ISSUE TITLE
Bug in NtQueryInformationProcess hook

### ISSUE THREAD

**Issue by mrexodia** [mrexodia/TitanHide#27]
https://forum.tuts4you.com/topic/40011-debugme-vmprotect-312-build-886-anti-debug-method-improved/#comment-192827

Affected functions:

- NtQuerySystemInformation
- NtQueryObject
- NtQueryInformationProcess

Basically in the kernel these functions put the `ReturnLength = x` *after* handling the rest so if we replace the actual result value where `ReturnLength == ResultPointer` it will return a different value.

See https://github.com/x64dbg/ScyllaHide/issues/47

**Comment by Mattiwatti** [comment]
(cont.'d from [x64dbg/ScyllaHide#47](https://github.com/x64dbg/ScyllaHide/issues/47) which was going more in the direction of TH discussion)

You can't really avoid race conditions regardless, unless you write each hook so that the entire buffer is first copied to kernel mode and the results only copied back after you are 100% done. This would imply:
1. Doing all input/parameter validation the same way the kernel does it, and in the same order
2. `ProbeForWrite` + copy to kernel mode buffer inside a `try/catch` block
3. **Doing all access checks manually**, because of (4):
4. Calling the **Zw** version of the function because your buffer now resides in kernel mode memory. If the kernel performs `ProbeForWrite` (i.e. every Nt syscall) on such a pointer this is a BSOD. If there is no Zw version, you need to write a `KeSetPreviousMode` to emulate it
5. Do the actual hooking stuff
6. Write back the results inside one or more `try/catch` blocks in the same order the kernel does it

Not worth it IMO, especially considering that if you assume someone is going to such lengths that they will create multiple threads to check if the buffer is modified twice, they could equally well make a decent estimate of the cost (in CPU ticks) of some syscall and notice that your hooked one is taking ~2 times as long as expected. Actually I'd say that's probably a more reliable way to detect hooking than trying to make a race condition happen.

So your code snippet looks fine to me IMO. You can minimize the number of potentially unneeded pointer dereferences by checking (A) if `ReturnLength` and `xxxInformation` overlap (this will exclude 99.99% of all cases except for intentional obfuscation behaviour caused by VMProtect and such), and (B) skipping the hook entirely if the `xxxInformationClass` is not relevant. I added a commit to ScyllaHide to do (B) as well for NtQIP and NtQueryObject, so the number of times the line `*ReturnLength = BackupReturnLength` is actually executed should be limited to a very small amount there.
