### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Jeekaz** [mrexodia/TitanHide#59]
![grafik](https://user-images.githubusercontent.com/85067119/120107156-30855e00-c160-11eb-9c61-11cd361dd283.png)

**Comment by Jeekaz** [comment]
any ideas?

**Comment by Mattiwatti** [comment]
The latest Visual Studio update broke the WDK. You can fix this by setting the 'external include path' manually in the project properties, but it's easier to do it in the WDK files because otherwise you'll need to fix every WDK project you ever open or make until they update the WDK again.

1. Close any open Visual Studio instances.
2. Go to `C:\Program Files (x86)\Windows Kits\10\build` and open `WindowsDriver.Win32.props` and `WindowsDriver.x64.props` (and `WindowsDriver.arm.props`/`WindowsDriver.arm64.props` if you have them) in a text editor. These files will start with something along the lines of
```
<PropertyGroup>
  <ExecutablePath >$(ExecutablePath);$(WDKBinRoot_x86);$(WDKContentRoot)tools\x86\Tracing</ExecutablePath>
</PropertyGroup>
  ```
Add an `ExternalIncludePath` attribute to the property groups so that they look like this:
```
<PropertyGroup>
  <ExecutablePath >$(ExecutablePath);$(WDKBinRoot_x86);$(WDKContentRoot)tools\x86\Tracing</ExecutablePath>
  <ExternalIncludePath>$(CRT_IncludePath);$(KM_IncludePath);$(KIT_SHARED_IncludePath)</ExternalIncludePath>
</PropertyGroup>
```
3. Save the files and reopen your project(s).

This should fix the problem.

**Comment by Jeekaz** [comment]
Thanks for that solution. It works fine now

Matthijs Lavrijsen ***@***.***> schrieb am So. 30. Mai 2021
um 22:35:
